default: &default
  adapter: <%= ENV.fetch('DATABASE_ADAPTER') { 'postgresql' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i %>
  timeout: 5000
  <% if ENV['DATABASE_PORT'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  <% end %>
  <% if ENV['DATABASE_USER'] %>
  username: <%= ENV['DATABASE_USER'] %>
  <% end %>
  <% if ENV['DATABASE_PASS'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  <% end %>
  <% if ENV['DATABASE_HOST'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  <% end %>
  <% if ENV['RAILS_ENV'] == 'production' || ENV['RAILS_ENV'] == 'staging' %>
  sslmode: 'verify-full'
  sslrootcert: /etc/ssl/certs/rds-combined-ca-bundle.pem
  <% end %>

<%= ENV.fetch('RAILS_ENV') { 'unknown' } %>:
  <<: *default
  database: <%= ENV['DATABASE_APP_DB'] %>

<%= ENV.fetch('RAILS_ENV') { 'unknown' } %>_cas:
  <<: *default
  database: <%= ENV['DATABASE_CAS_DB'] %>
