language: ruby

before_script:
  - cp config/letsencrypt_plugin.yml.sample config/letsencrypt_plugin.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - cp .rspec.travis .rspec

env:
  - RAILS_ENV=test DATABASE_ADAPTER=postgresql DATABASE_DB_TEST=boston_cas_test DEFAULT_FROM=greenriver.testing@mailinator.com

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
