language: ruby

before_script:
  - cp config/letsencrypt_plugin.yml.sample config/letsencrypt_plugin.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - mkdir app/assets/stylesheets/theme/styles
  - touch app/assets/stylesheets/theme/styles/_variables.scss
  - cp .rspec.travis .rspec

env:
  - RAILS_ENV=test DATABASE_ADAPTER=postgresql DATABASE_DB_TEST=boston_cas_test DEFAULT_FROM=greenriver.testing@mailinator.com DATABASE_WAREHOUSE_DB_TEST=test_hmis_warehouse

script:
  - createdb $DATABASE_WAREHOUSE_DB_TEST
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec

addons:
  postgresql: "9.5"