version: '3.4'

x-app: &app
  image: cas:0.0.2
  build:
    context: .
    args:
      RUBY_VERSION: 2.6.5
      PG_MAJOR: '12'
      NODE_MAJOR: '12'
      YARN_VERSION: '1.17.3'
      BUNDLER_VERSION: '1.17.3'
      ADDITIONAL_PACKAGES: vim nodejs python2 unzip xvfb google-chrome-stable less freetds-dev freetds-bin phantomjs xfonts-75dpi alien libpng-dev libicu-dev libcurl4-openssl-dev curl libmagic-dev libmagickcore-dev libmagickwand-dev
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
    REDIS_URL: redis://redis:6379/
    BOOTSNAP_CACHE_DIR: /bundle/bootsnap
    WEB_CONCURRENCY: 1
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
    CHROMEDRIVER_VERSION: 79.0.3945.36
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache

services:
  shell:
    <<: *backend
    command: /bin/bash
    entrypoint: ''
    depends_on:
      - db
      - redis

  console:
    <<: *backend
    stdin_open: true
    tty: true
    command: bundle exec rails console
    depends_on:
      - db
      - redis
      - mailhog

  web:
    <<: *backend
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
    expose:
      - 3000
    environment:
      <<: *env
      VIRTUAL_HOST: ${FQDN:-boston-cas.dev.test}
      VIRTUAL_PORT: 3000
    depends_on:
      - db
      - redis
      - mailhog

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PSQL_HISTFILE: /root/log/.psql_history
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - 6379

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    environment:
      VIRTUAL_HOST: mail.${FQDN:-boston-cas.dev.test}
      VIRTUAL_PORT: 8025
    expose:
      - 8025
      - 1025

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa

volumes:
  dbdata:
  redis:
  bundle:
  node_modules:
  rails_cache:

networks:
  default:
    external:
      name: nginx-proxy

