###
# Copyright Green River Data Group, Inc.
#
# License detail: https://github.com/greenriver/boston-cas/blob/stable/LICENSE.md
###

module MatchEvents
  class Created < Base
    # Just a simple event to mark the birth of the match

    def name
      'New match recommendation generated by CAS'
    end

    def contact_name
      'CAS Match Engine'
    end

  end
end
