development:
  adapter: async

test:
  adapter: test

<% redis_url = Rails.application.config_for(:cache_store)[:url] %>
production:
  adapter: redis
  url: <%= redis_url %>
  channel_prefix: boston_ca_production

staging:
  adapter: redis
  url: <%= redis_url %>
  channel_prefix: boston_ca_staging
