default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
  timeout: 5000
  <% if ENV['DATABASE_PORT'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  <% end %>
  <% if ENV['DATABASE_USER'] %>
  username: <%= ENV['DATABASE_USER'] %>
  <% end %>
  <% if ENV['DATABASE_PASS'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  <% end %>
  <% if ENV['DATABASE_HOST'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  <% end %>
  <% if ENV['RAILS_ENV'] == 'production' || ENV['RAILS_ENV'] == 'staging' %>
  sslmode: 'verify-full'
  sslrootcert: /etc/ssl/certs/rds-combined-ca-bundle.pem
  <% end %>

development:
  <<: *default
  database: <%= ENV['DATABASE_APP_DB'] %>

staging:
  <<: *default
  database: <%= ENV['DATABASE_APP_DB'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_APP_DB'] %>

development_warehouse:
  <<: *default
  database: <%= ENV['DATABASE_WAREHOUSE_DB'] %>
  <% if ENV['DATABASE_WAREHOUSE_PORT'] %>
  port: <%= ENV['DATABASE_WAREHOUSE_PORT'] %>
  <% end %>

staging_warehouse:
  <<: *default
  database: <%= ENV['DATABASE_WAREHOUSE_DB'] %>
  <% if ENV['DATABASE_WAREHOUSE_PORT'] %>
  port: <%= ENV['DATABASE_WAREHOUSE_PORT'] %>
  <% end %>

production_warehouse:
  <<: *default
  database: <%= ENV['DATABASE_WAREHOUSE_DB'] %>
  <% if ENV['DATABASE_WAREHOUSE_PORT'] %>
  port: <%= ENV['DATABASE_WAREHOUSE_PORT'] %>
  <% end %>

test:
  <<: *default
  database: <%= ENV['DATABASE_DB_TEST'] %>

test_warehouse:
  <<: *default
  database: <%= ENV['DATABASE_WAREHOUSE_DB_TEST'] %>
