<% if ENV['EXCEPTION_WEBHOOK_URL'] && ENV['EXCEPTION_WEBHOOK_CHANNEL'] %>
<%= ENV['RAILS_ENV'] %>:
  slack:
    webhook_url: <%= ENV['EXCEPTION_WEBHOOK_URL'] %>
    channel: '<%= '#' + ENV.fetch('EXCEPTION_WEBHOOK_CHANNEL_OVERRIDE', ENV['EXCEPTION_WEBHOOK_CHANNEL']) %>'
    additional_parameters:
      mrkdwn: true
      icon_url: <%= ENV.fetch('EXCEPTION_WEBHOOK_ICON') %>
<% end %>
