class ClientOpportunityMatchContact < ActiveRecord::Base
  # join model that represents the dedicated contact list for an
  # individual match.  These are automatically generated by the system
  # when the match was created and can be reviewed and updated by DND staff

  belongs_to :match, class_name: 'ClientOpportunityMatch', required: true, inverse_of: :client_opportunity_match_contacts
  belongs_to :contact, required: true, inverse_of: :client_opportunity_match_contacts

  include ContactJoinModel

  acts_as_paranoid

  def self.text_search(text)
    return none unless text.present?

    contact_matches = Contact.where(
      Contact.arel_table[:id].eq(arel_table[:contact_id]),
    ).text_search(text).exists

    where(contact_matches)
  end
end
