name: Audit and Test

on: pull_request
jobs:
  build:
    runs-on: ubuntu-18.04
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up dependancies
      env:
        DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
      run: |
        sudo apt-get update
        sudo apt-get install \
          redis-server \
          libmagic-dev \
          libpq-dev
        sudo -upostgres createuser -h postgres --echo --superuser $USER #give the runner
        createdb -h postgres --echo
        createdb -h postgres $DATABASE_WAREHOUSE_DB_TEST
        gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
        gem install bundler -v '< 2'
    - name: 'Install gems'
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run bundle-audit
      run: |
        bundle exec bundle-audit check --update --ignore CVE-2019-16676 CVE-2017-1002201
    - name: Run brakeman
      run: |
        bundle exec brakeman -q --ensure-latest --no-pager --except PermitAttributes,Render
    - name: 'App setup'
      run: |
        cp config/secrets.yml.sample config/secrets.yml
        mkdir app/assets/stylesheets/theme/styles
        touch app/assets/stylesheets/theme/styles/_variables.scss
        cp .rspec.travis .rspec
    - name: Prepare test db
      env:
        RAILS_ENV: test
        DATABASE_ADAPTER: postgresql
        DATABASE_HOST: postgres
        DATABASE_DB_TEST: boston_cas_test
        DEFAULT_FROM: greenriver.testing@mailinator.com
        DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
        HOSTNAME: openpath.host
        PORT: 80
      run: |
        bundle exec rake db:drop db:create db:schema:load
    - name: Run tests
      env:
        RAILS_ENV: test
        DATABASE_ADAPTER: postgresql
        DATABASE_HOST: postgres
        DATABASE_DB_TEST: boston_cas_test
        DEFAULT_FROM: greenriver.testing@mailinator.com
        DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
        HOSTNAME: openpath.host
        PORT: 80
      run: |
        bundle exec rspec
