name: Bundle Audit and Brakeman

on:
  push:
    branches:
      - '*'
      - '**/*'
  # NOTE: you don't need to build all PRs if you are also building all branches
  # pull_request:
  #   branches:
  #     - '*'
  #     - '**/*'
jobs:
  build:
    runs-on: ubuntu-20.04
    # Docker Hub image that the job executes in
    container: ruby:2.7.2-slim-buster

    # Service containers to run with job
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASS: postgres
          POSTGRES_MULTIPLE_EXTENSIONS: hstore
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Set up dependancies
        env:
          DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
          DATABASE_DB_TEST: boston_cas_test
        run: |
          apt-get update
          apt-get install -y \
            libmagic-dev \
            libpq-dev

          echo "postgres:5432:*:postgres:postgres" > ~/.pgpass
          chmod 600 ~/.pgpass

          gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
          gem install bundler -v '< 2'
      - uses: actions/checkout@v2
      - name: 'Install gems'
        run: |
          bundle install --jobs 4 --retry 3
      - name: Run bundle-audit
        run: |
          bundle exec bundle-audit check --update --ignore CVE-2019-16676 CVE-2017-1002201
      - name: Run brakeman
        run: |
          bundle exec brakeman -q --ensure-latest --no-pager --except PermitAttributes,Render
