name: Rails Tests

on:
  push:
    branches:
      - '*'
      - '**/*'
  # NOTE: you don't need to build all PRs if you are also building all branches
  # pull_request:
  #   branches:
  #     - '*'
  #     - '**/*'
jobs:
  build:
    runs-on: ubuntu-20.04
    # Docker Hub image that the job executes in
    container: ruby:2.7.2-slim-buster

    # Service containers to run with job
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASS: postgres
          POSTGRES_MULTIPLE_EXTENSIONS: hstore
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Set up dependancies
        env:
          DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
          DATABASE_DB_TEST: boston_cas_test
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            curl \
            freetds-bin \
            freetds-dev \
            git \
            icu-devtools \
            imagemagick \
            libc6-dev \
            libcurl4-openssl-dev \
            libgeos-dev \
            libicu-dev \
            libmagic-dev \
            libpq-dev \
            libproj-dev \
            postgis \
            postgresql-client \
            python \
            unzip \
            wkhtmltopdf

          echo "postgres:5432:*:postgres:postgres" > ~/.pgpass
          chmod 600 ~/.pgpass

          gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
          gem install bundler -v '< 2'
      - uses: actions/checkout@v2
    - name: 'Install gems'
      run: |
        bundle install --jobs 4 --retry 3
    - name: 'App setup'
      run: |
        cp config/secrets.yml.sample config/secrets.yml
        mkdir app/assets/stylesheets/theme/styles
        touch app/assets/stylesheets/theme/styles/_variables.scss
        cp .rspec.travis .rspec
    - name: Prepare test db
      env:
        RAILS_ENV: test
        DATABASE_ADAPTER: postgresql
        DATABASE_DB_TEST: boston_cas_test
        DEFAULT_FROM: greenriver.testing@mailinator.com
        DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
        HOSTNAME: openpath.host
        PORT: 80
      run: |
        bundle exec rake db:drop db:create db:schema:load
    - name: Run tests
      env:
        RAILS_ENV: test
        DATABASE_ADAPTER: postgresql
        DATABASE_DB_TEST: boston_cas_test
        DEFAULT_FROM: greenriver.testing@mailinator.com
        DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
        HOSTNAME: openpath.host
        PORT: 80
      run: |
        bundle exec rspec
