name: Rails Tests

on:
  push:
    branches:
      - '*'
      - '**/*'
concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-24.04
    # Docker Hub image that the job executes in
    container: ruby:3.4.5-slim-bookworm

    # Service containers to run with job
    services:
      postgres:
        image: index.docker.io/library/postgres@sha256:bcb90dc18910057ff49ce2ea157d8a0d534964090d39af959df41083f18c3318 # 17.5-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASS: postgres
          POSTGRES_MULTIPLE_EXTENSIONS: hstore
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: index.docker.io/library/redis@sha256:02419de7eddf55aa5bcf49efb74e88fa8d931b4d77c07eff8a6b2144472b6952 # alpine
        ports:
          - 6379:6379

    env:
      DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
      DATABASE_DB_TEST: boston_cas_test
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 'Container Setup'
        id: container-setup
        uses: ./.github/workflows/container_setup

      - name: Prepare test db
        run: |
          pg_isready -h postgres -U postgres
          bin/db_prep

          echo "Setting up .pgpass"
          echo "postgres:*:*:postgres:postgres" > ~/.pgpass
          chmod 600 ~/.pgpass

      - name: 'App setup'
        run: |
          cp config/secrets.yml.sample config/secrets.yml
          mkdir app/assets/stylesheets/theme/styles
          touch app/assets/stylesheets/theme/styles/_variables.scss
          cp .rspec.ci .rspec

      - name: Prepare test db
        env:
          RAILS_ENV: test
          DATABASE_ADAPTER: postgresql
          DATABASE_DB_TEST: boston_cas_test
          DATABASE_HOST: postgres
          DATABASE_PASS: postgres
          DATABASE_USER: postgres
          PGPASSWORD: postgres
          DEFAULT_FROM: greenriver.testing@mailinator.com
          DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
          HOSTNAME: openpath.host
          PORT: 80
        run: |
          bundle exec rails db:drop db:create db:schema:load db:migrate
          createdb -h $DATABASE_HOST -U $DATABASE_USER $DATABASE_WAREHOUSE_DB_TEST
          bundle exec rails assets:precompile
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_ADAPTER: postgresql
          DATABASE_HOST: postgres
          DATABASE_PASS: postgres
          DATABASE_USER: postgres
          DATABASE_DB_TEST: boston_cas_test
          DEFAULT_FROM: greenriver.testing@mailinator.com
          DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
          HOSTNAME: openpath.host
          FQDN: openpath.host
          PORT: 80
        run: |
          bundle exec rspec
