name: Rails Tests

on:
  push:
    branches:
      - '*'
      - '**/*'
concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    # Docker Hub image that the job executes in
    container: ruby:3.3.7-alpine3.20

    # Service containers to run with job
    services:
      postgres:
        image: index.docker.io/library/postgres@sha256:236985828131e95a12914071b944d0e0d21da5281312292747e222845f0ea670 # 13-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASS: postgres
          POSTGRES_MULTIPLE_EXTENSIONS: hstore
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: index.docker.io/library/redis@sha256:02419de7eddf55aa5bcf49efb74e88fa8d931b4d77c07eff8a6b2144472b6952 # alpine
        ports:
          - 6379:6379

    env:
      DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
      DATABASE_DB_TEST: boston_cas_test
    steps:
      - name: Install git
        run: |
          apk add --no-cache git
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up dependencies

        run: |
          apk add --no-cache $(cat .github/dependencies.txt)

          echo "postgres:5432:*:postgres:postgres" > ~/.pgpass
          chmod 600 ~/.pgpass

          yarn install --frozen-lockfile

      - name: cache gems
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        id: gemcache
        with:
          path: |
            vendor/bundle
            /usr/local/bundle/
          key: ${{ runner.os }}-gemcache-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/.ruby-version') }}

      - name: Install gems
        run: |
          gem install bundler --version=2.6.3
          bundle config set --local without 'production staging development'
          bundle install --jobs 4 --retry 3

      - name: 'App setup'
        run: |
          cp config/secrets.yml.sample config/secrets.yml
          mkdir app/assets/stylesheets/theme/styles
          touch app/assets/stylesheets/theme/styles/_variables.scss
          cp .rspec.travis .rspec
      - name: Prepare test db
        env:
          RAILS_ENV: test
          DATABASE_ADAPTER: postgresql
          DATABASE_DB_TEST: boston_cas_test
          DATABASE_HOST: postgres
          DATABASE_PASS: postgres
          DATABASE_USER: postgres
          PGPASSWORD: postgres
          DEFAULT_FROM: greenriver.testing@mailinator.com
          DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
          HOSTNAME: openpath.host
          PORT: 80
        run: |
          bundle exec rails db:drop db:create db:schema:load db:migrate
          createdb -h $DATABASE_HOST -U $DATABASE_USER $DATABASE_WAREHOUSE_DB_TEST
          bundle exec rails assets:precompile
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_ADAPTER: postgresql
          DATABASE_HOST: postgres
          DATABASE_PASS: postgres
          DATABASE_USER: postgres
          DATABASE_DB_TEST: boston_cas_test
          DEFAULT_FROM: greenriver.testing@mailinator.com
          DATABASE_WAREHOUSE_DB_TEST: test_hmis_warehouse
          HOSTNAME: openpath.host
          FQDN: openpath.host
          PORT: 80
        run: |
          bundle exec rspec
